// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvw15UYV5yj8XB9_wJM9xMaxPd2O932MQ',
    appId: '1:542725343091:web:605938507cae731082a706',
    messagingSenderId: '542725343091',
    projectId: 'skanmed-14b16',
    authDomain: 'skanmed-14b16.firebaseapp.com',
    storageBucket: 'skanmed-14b16.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDskhyUm_zYVmF-WQSIPUKzyxfK8287fKo',
    appId: '1:542725343091:android:a305504a97c0cdf782a706',
    messagingSenderId: '542725343091',
    projectId: 'skanmed-14b16',
    storageBucket: 'skanmed-14b16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIVbHcAZGW0Sj8XYAnsxEGe0xIKuIW8qA',
    appId: '1:542725343091:ios:b5f54ed1da783bca82a706',
    messagingSenderId: '542725343091',
    projectId: 'skanmed-14b16',
    storageBucket: 'skanmed-14b16.appspot.com',
    iosClientId: '542725343091-ae0d11ga8anvrivjqj1108gmtp7pnoia.apps.googleusercontent.com',
    iosBundleId: 'com.example.skanmed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIVbHcAZGW0Sj8XYAnsxEGe0xIKuIW8qA',
    appId: '1:542725343091:ios:b5f54ed1da783bca82a706',
    messagingSenderId: '542725343091',
    projectId: 'skanmed-14b16',
    storageBucket: 'skanmed-14b16.appspot.com',
    iosClientId: '542725343091-ae0d11ga8anvrivjqj1108gmtp7pnoia.apps.googleusercontent.com',
    iosBundleId: 'com.example.skanmed',
  );
}
